example_metric_objective:
  _target_: nuplan.planning.training.modeling.objectives.example_metric_objective.ExampleMetricObjective
  _convert_: 'all'

  entropy_weight: 40
  kl_weight: 20
  use_FDEADE_aux_loss: true

  metric:
    _target_: nuplan.planning.metrics.evaluation_metrics.common.drivable_area_compliance.DrivableAreaComplianceStatistics
    _convert_: 'all'
    name: 'drivable_area_compliance'
    category: 'Planning'
    metric_score_unit: 'bool'

    max_violation_threshold: 0.3 # The violatation tolerance threshold in meters


    # Parameter: base metric name and other high level metrics used in this metric
    lane_change_metric:
        _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_lane_change.EgoLaneChangeStatistics
        _convert_: 'all'
        name: 'ego_lane_change'
        category: 'Planning'
        max_fail_rate: 0.3
