defaults:
    - low_level: # Low level metrics
        - ego_lane_change_statistics
        - ego_jerk_statistics
        - ego_lat_acceleration_statistics
        - ego_lon_acceleration_statistics
        - ego_lon_jerk_statistics
        - ego_yaw_acceleration_statistics
        - ego_yaw_rate_statistics
        
    - high_level:  # High level metrics that depend on low level metrics, they can also rely on the previously called high level metrics
        - drivable_area_compliance_statistics
        - speed_limit_compliance_statistics
        - ego_is_comfortable_statistics
        - driving_direction_compliance_statistics
